### PR TITLE
add grf plan initialization

### PR DESCRIPTION
**Pull request by jrenaf**

### CODE REVIEW

**Review by jcnorby — CHANGES_REQUESTED** [review]
Remove pybind11 submodule in this branch, otherwise looks good.

**Comment by yanhaoy** [comment]
Can you initialize the x and y components of grf_plan_ to zero?

**Comment by jrenaf** [comment]
Changes have been applied.

**Comment by jrenaf** [comment]
The body mass is assigned after initialization, could we put that before it?

**Review by jcnorby — APPROVED** [review]

**Pull request merged**
